version: '3.8'

services:
  maroon:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: scti_front
    command: yarn dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/scti
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '10'
